### ISSUE TITLE
WRS2019 ToDo List

### ISSUE THREAD

**Issue by RyodoTanaka** [WRS-TNK/Memo#10]
WRS2019 @長岡 に向けたやることTodo List

- [x] DoubleArmのURDF化
- [x] DoubleArm, AizuApiderのMoveitプロファイル作成
- [x] 各タスクのcnoidを作る
- [x] DoubleArm, Aizuの２つが同時に起動できることをすべてのタスクで確認
- [x] ROSコントローラ（去年までので良い）を構築する．必ず荷台同時に出来ることを確認すること．
- [x] ROSメッセージブリッジを作る
- [x] DoubleArmにセンサ追加して，ROS側から観測する．
- [x] ARマーカー読み取りノードを忘れない
- [x] 遠隔操作の確認
- [x] PointCloudの保存とかそういう系ツールの環境構築（README作りながらやる）
- [x] bring up リポジトリの作成
- [x] JointTrajectoryブリッジを作る
- [x] Moveit利用したコントローラ周りを作り込む
- [ ] ヘッドマウントの実装

**Comment by RyodoTanaka** [comment]
DoubleArmのモデルでけた！！
完全勝利！！
![Screenshot from 2019-08-15 17-16-37](https://user-images.githubusercontent.com/8377208/63082786-1b870d00-bf82-11e9-868c-73ad8c5090dd.png)
https://github.com/WRS-TNK/wrs_tnk_robot

**Comment by RyodoTanaka** [comment]
そう言えば JointPositionブリッジいらねーは
というのも，rqt tools に JointTrajectoryに設定されてるJointをまるでJointPositionみたいに扱えるやつがあるのでそれで良い．

**Comment by RyodoTanaka** [comment]
それから
やっぱりAIzuいらなくねーか...？
というお気持ちになってきているので，Moveit!プロファイルは一旦DoubleArmだけにします

**Comment by shimoe** [comment]
問題になりそうなのはQRコードですかね？

cnoidもDoubleArmをスポーンさせるようにします

**Comment by RyodoTanaka** [comment]
そういえばそうか...！
DoubleArmの手先にカメラつけるは
せっかくやからDepthつける...？
いや，やっぱいらんか

プライオリティはMoveit!の設定ファイルを優先します．

cnoidマン頼んだ！

**Comment by RyodoTanaka** [comment]
Aizu採用するかどうかは DoubleArmにカメラ付けてやってみてからにするは

**Comment by shimoe** [comment]
- [x] rossever設定&PC2台での動作確認
- [x] LiDARとカメラ、jointstateのトピック確認

**Comment by RyodoTanaka** [comment]
HMDだけは完全にスルーやったな...
ビルドもできてるのに...
ただ超絶進捗した．
まじおつかれ！
